#!/bin/bash

nomFichierEntrant=bieres.csv
nomFichierSortant=bieres.html
delimiteur=';'

while getopts "d:s:S:" option
do
    case $option in
        d)	
			delimiteur=${OPTARG}
			;;
		s)
			trie="| sort -t $delimiteur -k ${OPTARG} "
			;;
		S)
			trie="| sort -t $delimiteur -k $(sed -n 1p bieres.csv | tr ";" "\n" | grep -in ${OPTARG} | cut -d : -f1  | head -n 1)"
			;;
		*)
			delimiteur=';'
			;;
	esac
done

echo $trie

echo "<!doctype html>
<html lang=\"fr\">
<head>
	<meta charset=\"utf-8\">
	<title>bieres</title>
</head>
<body>
	<table>

		$(sed -n 1p $nomFichierEntrant | sed -e "s/^/<tr><th>/" -e "s/$delimiteur/<\/th><th>/g" -e 's/$/<\/th><\/tr>/')
		$(sed 1d $nomFichierEntrant $trie |  sed -e "s/^/<tr><td>/" -e "s/$delimiteur/<\/td><td>/g" -e 's/$/<\/td><\/tr>/')

	</table>
</body>
</html>" > $nomFichierSortant