#!/bin/bash

#On récupere le nom des fichiers entrant et sortant
nomFichierEntrant=bieres.csv
nomFichierSortant=bieres.html
#On détermine le délimitateur
delimiteur=';'

#On vérifie les options entrées
while getopts "d:s:S:" option
do
    case $option in
        d)	
			delimiteur=$OPTARG
			;;
		s)
			#La variable trie est initialisée de façon à ajouter le trie 
			#par le numero de colonne($OPTARG) séparé par le délimiteur($delimiteur) donné en parametre 
			trie="| sort -t $delimiteur -k $OPTARG "
			;;
		S)
			#On trie par nom de colonne($OPTARG) donné en parametre
			#Pour cela on récupere la premiere ligne du fichier csv
			#On remplace le délimiteur par un retour chariot
			#On affiche les lignes (-n) et on cherche le nom de colonne avec grep en ignorant la casse (-i)
			#On récupere uniquement le numero de ligne avec $(cut -d : -f1)
			#Si on a plusieurs noms équivalent on récupere le premier avec $(head -n 1)
			trie="| sort -t $delimiteur -k $(sed -n 1p $nomFichierEntrant | tr ";" "\n" | grep -in $OPTARG | cut -d : -f1  | head -n 1)"
			;;
		*)
			delimiteur=';'
			;;
	esac
done

#On affiche le contenu du fichier entrant dans un fichier sortant sous la forme d'un tableau en HTML
#Explication des commandes effectuées:
#	sed -n 1p $nomFichierEntrant recupere la premiere ligne du fichier
#	sed 1d $nomFichierEntrant $trie recupere le contenu du fichier sans la premiere ligne et trie si necessaire
#	sed -e "s/^/\t\t<tr>\n\t\t\t<th>/" ajoute "\t\t<tr>\n\t\t\t<th>" au début de ligne
#	sed -e "s/$delimiteur/<\/th>\n\t\t\t<th>/g" remplace le délimiteur par "<\/th>\n\t\t\t<th>" pour chaque occurence
#	sed -e 's/$/<\/th>\n\t\t<\/tr>/ ajoute "<\/th>\n\t\t<\/tr>" à la fin de la ligne
echo "<!doctype html>
<html lang=\"fr\">
<head>
	<meta charset=\"utf-8\">
	<title>$nomFichierSortant</title>
</head>
<body>
	<table>
$(sed -n 1p $nomFichierEntrant | sed -e "s/^/\t\t<tr>\n\t\t\t<th>/" -e "s/$delimiteur/<\/th>\n\t\t\t<th>/g" -e 's/$/<\/th>\n\t\t<\/tr>/')
$(sed 1d $nomFichierEntrant $trie |  sed -e "s/^/\t\t<tr>\n\t\t\t<td>/" -e "s/$delimiteur/<\/td>\n\t\t\t<td>/g" -e 's/$/<\/td>\n\t\t<\/tr>/')
	</table>
</body>
</html>" > $nomFichierSortant