#!/bin/bash

nomFichierEntrant=bieres.csv
nomFichierSortant=bieres.html
delimiteur=';'

if(($# != 0))
then
	if(($1 == '-d'))
	then
		delimiteur=$2
		shift
		shift
	fi

	if(($1 == '-s'))
	then
		echo trie avec numero de colonne
		numColonneTrie=$2
		shift
		shift
	fi


	if(($1 == '-S'))
	then
		echo trie avec nom
		nomColonneTrie=$2
		shift
		shift
	fi
fi




echo "<!doctype html>
<html lang=\"fr\">
<head>
	<meta charset=\"utf-8\">
	<title>bieres</title>
</head>
<body>
	<table>

		$(sed -n 1p $nomFichierEntrant | sed -e "s/^/<tr><th>/" -e "s/$delimiteur/<\/th><th>/g" -e 's/$/<\/th><\/tr>/')
		$(sed 1d $nomFichierEntrant | sed -e "s/^/<tr><td>/" -e "s/$delimiteur/<\/td><td>/g" -e 's/$/<\/td><\/tr>/')

	</table>
</body>
</html>" > $nomFichierSortant