#!/bin/bash

recursiveSearch() {
 
    for file in "$1"/*
    do
 
        if [ -d "$file" ]
	then
	    echo "$2" "$file"
            recursiveSearch "$file" "    $2"
        else
	    echo "$2" "`basename $file`"
	 fi
 
    done
}

recursiveSearch "$1" ""
