#!/bin/bash

port=$1
cheminRacine=$2
cheminModele=$3

PATH=$(cd $(dirname $0) ; pwd):$PATH

rm /tmp/requete

tube=/tmp/requete

mkfifo $tube

while true
do
	cat $tube | process-request | nc.openbsd -l 127.0.0.1 $port > $tube
done