#!/bin/bash
removeSlash(){
	
	longueur=$(echo "$1" | wc -c)
	longueur=$(echo $(($longueur-1)))

	if [ $(echo "$1" | cut -c "$longueur") = '/' ]
	then
		echo "$1" | sed 's/.$//'
	else
		echo "$1"
	fi 
}

#On définie les variables par défaut
port="8080"
cheminRacine="$(pwd)"
cheminModele="$(pwd)/modele.html"


#On vérifie les options entrées
while getopts ":d:p:t:" option
do
    case $option in
		d)
			#Si l'option -d est entrée on modifie le chemin vers la racine des fichiers à donner
			cheminRacine=${OPTARG}
			;;
		p)	
			#Si l'option -p est entrée on modifie le port d'écoute du serveur
			port=${OPTARG}
			;;
		t)
			#Si l'option -t est entrée on modifie le chemin du modele HTML utilisé
			cheminModele=${OPTARG}
			;;
		*)
			#Si l'option -h est entrée on ajoute  
			if [ "$1" = "-h" ]
			then
				help="ok"
			fi
			;;
	esac
done

cheminRacine=$(removeSlash "$cheminRacine")
cheminModele=$(removeSlash "$cheminModele")

#si la variable help n'est pas nulle on affiche l'aide
if [ ! -z "$help" ]
then
	echo "Server HTTP - Permet de lancer le serveur  
Utilisation: http-server [-d 〈chemin〉] [-p〈port〉] [-t 〈chemin〉]
Résumé des commandes:
	-d 	〈chemin〉 spécifiant la 〈racine〉 contenant les fichiers servis
	-h 	 aide
	-p 	〈port〉 spécifiant le port d’écoute
	-t 	〈chemin〉 spécifiant l’emplacement du modèle utilisé par générer les pages HTML"
fi
			
#On appel le script get-request avec en parametre les options 
get-request "$port" "$cheminRacine" "$cheminModele"