#!/bin/bash

set -x

corps="<!doctype html><ul>"
dossier="$1"
for nom in "$dossier"/*
do
	extension=$(echo -n "$nom" | tail -c 3)

	echo "$extension"

	if [ "$extension" == 'csv' ]
	then
		corps="$corps<li><a href=\"http://localhost:8080/html/$(basename "$nom")\">$(basename "$nom")</a></li>"
	fi
	if [ -d "$nom" ]
	then
		corps="$corps<li><a href=\"http://localhost:8080/html/$(basename "$nom")\">$(basename "$nom")</a></li>"

	fi
	if [ "$extension" == 'txt' ]
	then
		corps="$corps<li><a href=\"http://localhost:8080/html/$(basename "$nom")\">$(basename "$nom")</a></li>"
	else
		corps="$corps<li><a href=\"http://localhost:8080/contenu/$(basename "$nom")\">$(basename "$nom")</a></li>"
	fi

done
corps="$corps</ul>"
echo "$corps"