#!/bin/bash

modele="$1"
debut="--DEBUT_REMPLACEMENT--"
fin="--FIN_REMPLACEMENT--"

sed -e "/$fin/ r$/dev/stdin" -e "/$debut/,/$fin/ d" |
sed -re 's!\*(.+)\*!<strong>\1</strong>!g' -e 's!"(.+)"!<em>\1</em>!g'
